logging:
  level:
    root: INFO
    com.jozard: INFO
    org.telegram.telegrambots.updatesreceivers.DefaultBotSession: INFO

botConfig:
  token: ${REMINDER_POLL_BOT_TOKEN}

app:
  datasource:
    jdbc-url: ${DATABASE_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    pool-size: 5
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
